### PR TITLE
Added request ID to RouteServlet

### PR DESCRIPTION
**Pull request by vania-pooh**

### CODE REVIEW

**Comment by vania-pooh** [comment]
btw, the build http://ci.qatools.ru/job/gridrouter_build-war/74/console has passed.

**Comment by smecsia** [comment]
http://ci.qatools.ru/job/gridrouter_build-war/ru.qatools.seleniumkit$gridrouter-proxy/74/testReport/junit/ru.qatools.gridrouter/StatsServletTest/testEvictionOfOldSession/

**Comment by vania-pooh** [comment]
@smecsia will take a look tomorrow.

**Comment by vania-pooh** [comment]
All this stuff with broken tests needs to be investigated independently. These tests are unstable: they always fail on my Mac, but pass on Linux even with my changes. I opt for merging this.

**Pull request merged**
