### PR TITLE
Calculate running sessions per user

### PR DESCRIPTION
**Pull request by innokenty**
### 1. Calculate running sessions for each (user; browser; version)
Change the behavior of the ```/stats```: accept only logged in users and return a json as the result which maps browser names to browser versions and then to the number of sessions that users has currently running. Like that:

```
$ curl http://user:password@gridrouter.host/stats
```
⬇︎
```json
{
  "chrome" : {
    "45.0" : 1
  },
  "firefox" : {
    "33.0" : 2,
    "34.0" : 7
  }
}
```

The old sessions that are not updated are evicted from the map after the timeout that can be configured by property ```grid.router.evict.sessions.timeout.seconds``` with defaults to 2 minutes.

Providing a different session storage than default in-memory implementation should work in a distributed multi-headed Grid Router runtime if properly synchronized via any library chosen.

### 2. Provide hub error message to client

Respond to the client with the error message returned by the last hub tried, when unable to create new session on any hub. Instead of just responding with the default error message which does not help a lot.

### CODE REVIEW

**Comment by innokenty** [comment]
call @baev @eroshenkoam @smecsia

**Comment by innokenty** [comment]
Sonar finally noticed that we have a 100+ lines long method in RouteServlet :)

**Comment by innokenty** [comment]
And also it finally has noticed that all our ```@Autowired``` servlet fields are not ```@Serializable```.

**Comment by smecsia** [comment]
@baev Sonar is right. Servlet fields must be `Serializable`, so it's a bad idea to autowire them.

**Comment by innokenty** [comment]
Despite these persisting Sonar issues PR is finally ready to merge.

**Comment by innokenty** [comment]
Test this please

**Comment by innokenty** [comment]
These quota reload tests again >_<

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
test this please

**Comment by innokenty** [comment]
test this please

**Pull request merged**
